version: 0.2

phases:

  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 155409188015.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - docker build -t food-website .
      - docker tag food-website:latest 155409188015.dkr.ecr.ap-south-1.amazonaws.com/food-website:latest

  post_build:
    commands:
      - docker push 155409188015.dkr.ecr.ap-south-1.amazonaws.com/food-website:latest
      - aws eks update-kubeconfig --region ap-south-1 --name food-cluster
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
